kind: Service
apiVersion: v1
metadata:
  name: nginx-537-004-100-0
  namespace: 537-004-100-0
  labels:
    app: nginx
    role: 537-004-100-0
    env: test
spec:
  type: ClusterIP
  selector:
    app: nginx
    role: 537-004-100-0
  ports:
    - port: 80
      targetPort: 80