apiVersion: v1
kind: Service
metadata:
  name: diamondweb
  namespace: $TARGET_ROLE
  labels:
    app: diamondweb-service
    role: $TARGET_ROLE
spec:
  type: LoadBalancer
  selector:
    app: diamondweb
    role: $TARGET_ROLE
  ports:
    - port: 80
      targetPort: 80
